### ISSUE TITLE
Upload raw glint360k?

### ISSUE THREAD

**Issue by sporadicCactus** [tamerthamoqa/facenet-pytorch-glint360k#18]
Hi!

I would like to experiment with using different alignment strategies and more powerful detection/alignment models. For that it would be nice to have raw glint360k dataset. However, it is hard to get access to: the torrent is pretty much dead, and baidu is not very cooperative.

Would it be possible for you to upload raw glint360k to Google Drive?

**Comment by tamerthamoqa** [comment]
Hello @sporadicCactus 

I was thinking of upgrading my Google Drive storage capacity anyway, so might as well upload the raw unpackaged glint360k data. The download link will be available within the next few days hopefully.

**Comment by tamerthamoqa** [comment]
Hello @sporadicCactus 

I have uploaded the dataset and it is available [here](https://drive.google.com/file/d/1VV5uUIz-_1lEeir8TOosfR6XfecaMGkR/view?usp=sharing). I have added the link to the README.

**Comment by sporadicCactus** [comment]
Hi @tamerthamoqa

Thanks a lot! I will provide my align/crop script when I am done tinkering with it.
